In [13]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

In [6]:
load_data = pd.read_csv('./data/train.csv')

## Data Load

In [9]:
load_data.head(40)

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Shetland Sheepdog Mix,Brown/White
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,Spayed Female,1 year,Domestic Shorthair Mix,Cream Tabby
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,Neutered Male,2 years,Pit Bull Mix,Blue/White
3,A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Cream
4,A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,Dog,Neutered Male,2 years,Lhasa Apso/Miniature Poodle,Tan
5,A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,Dog,Intact Female,1 month,Cairn Terrier/Chihuahua Shorthair,Black/Tan
6,A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Tabby
7,A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,Cat,Unknown,3 weeks,Domestic Shorthair Mix,Brown Tabby
8,A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,Dog,Spayed Female,5 months,American Pit Bull Terrier Mix,Red/White
9,A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,Dog,Spayed Female,1 year,Cairn Terrier,White
10,A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Black
11,A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,Dog,Spayed Female,2 years,Miniature Schnauzer Mix,Silver
12,A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,Dog,Neutered Male,4 years,Pit Bull Mix,Brown
13,A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,Dog,Neutered Male,2 years,Yorkshire Terrier Mix,Black/Red
14,A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Great Pyrenees Mix,White/Cream
15,A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Orange Tabby/White
16,A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby
17,A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,Dog,Intact Female,2 weeks,Pit Bull Mix,Brown/White
18,A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,Cat,Intact Female,2 years,Angora Mix,White
19,A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Flat Coat Retriever Mix,Black
20,A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,Dog,Intact Male,2 months,Queensland Heeler Mix,Black/White
21,A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,Cat,Spayed Female,1 year,Domestic Shorthair Mix,White
22,A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,Dog,Spayed Female,2 years,Plott Hound/Boxer,Brown Brindle/White
23,A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,Dog,Neutered Male,10 months,German Shepherd Mix,Brown/White
24,A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,Dog,Neutered Male,2 months,German Shepherd Mix,Black/Brown
25,A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,Cat,Intact Female,1 month,Domestic Shorthair Mix,Orange Tabby
26,A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,Dog,Spayed Female,6 months,American Staffordshire Terrier Mix,Chocolate/White
27,A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,Dog,Spayed Female,5 years,Chihuahua Shorthair Mix,White/Tan
28,A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Cream Tabby/White
29,A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,Cat,Neutered Male,7 years,Russian Blue Mix,Blue
30,A718535,NaN,2016-01-01 13:57:00,Euthanasia,Suffering,Cat,Spayed Female,3 years,Domestic Shorthair Mix,Calico
31,A707341,Murphy,2015-07-15 15:25:00,Transfer,Partner,Dog,Intact Male,4 months,Labrador Retriever Mix,Black/White
32,A682532,NaN,2014-07-03 17:01:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Torbie
33,A666825,Jesse,2013-11-08 13:24:00,Return_to_owner,NaN,Dog,Neutered Male,5 years,Collie Smooth/German Shepherd,Brown/Black
34,A699723,Delgado,2015-04-11 16:01:00,Transfer,Partner,Dog,Neutered Male,3 years,Chihuahua Shorthair Mix,Brown
35,A668626,NaN,2013-12-06 14:55:00,Euthanasia,Suffering,Dog,Intact Male,3 years,Labrador Retriever Mix,Yellow
36,A657085,Pony Boy,2013-10-24 11:22:00,Return_to_owner,NaN,Dog,Neutered Male,3 years,Pit Bull Mix,Brown/White
37,A682413,NaN,2014-07-02 13:37:00,Transfer,Partner,Cat,Intact Male,2 months,Domestic Shorthair Mix,Blue/White
38,A702655,Mica,2015-08-11 00:00:00,Transfer,Partner,Cat,Neutered Male,4 months,Domestic Shorthair Mix,Black/White
39,A707503,NaN,2015-07-14 12:16:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby

### Nan Data 삭제

In [48]:
x_data = load_data.dropna()
len(x_data)

6979

In [51]:
data1 = []
for i in x_data['AgeuponOutcome'] :
    data = i.split(' ')
    #print(data)
    if('year' in data[1] ):
        data1.append(int(data[0]) * 365)
    elif('month' in data[1]):
        data1.append(int(data[0]) * 31)
    elif('week' in data[1]):
        data1.append(int(data[0]) * 7)
    elif('day' in data[1]):
        data1.append(int(data[0]))
        
len(data1)

6979

In [ ]:
def f(data):
    if('year' in data):
        return int(data) * 365
    elif('month' in data):
        return int(data) * 31
    elif('week' in data):
        return int(data) * 7
    elif('day' in data):
        return data

In [52]:
a = lambda x : f()
x_data['AgeuponOutcome'].apply(a)

1        <function <lambda> at 0x00000227485EE268>
2        <function <lambda> at 0x00000227485EE268>
5        <function <lambda> at 0x00000227485EE268>
6        <function <lambda> at 0x00000227485EE268>
12       <function <lambda> at 0x00000227485EE268>
15       <function <lambda> at 0x00000227485EE268>
18       <function <lambda> at 0x00000227485EE268>
20       <function <lambda> at 0x00000227485EE268>
21       <function <lambda> at 0x00000227485EE268>
25       <function <lambda> at 0x00000227485EE268>
31       <function <lambda> at 0x00000227485EE268>
34       <function <lambda> at 0x00000227485EE268>
38       <function <lambda> at 0x00000227485EE268>
42       <function <lambda> at 0x00000227485EE268>
60       <function <lambda> at 0x00000227485EE268>
61       <function <lambda> at 0x00000227485EE268>
62       <function <lambda> at 0x00000227485EE268>
66       <function <lambda> at 0x00000227485EE268>
67       <function <lambda> at 0x00000227485EE268>
71       <function <lambda> at 0x00000227485EE268>
75       <function <lambda> at 0x00000227485EE268>
80       <function <lambda> at 0x00000227485EE268>
82       <function <lambda> at 0x00000227485EE268>
84       <function <lambda> at 0x00000227485EE268>
86       <function <lambda> at 0x00000227485EE268>
92       <function <lambda> at 0x00000227485EE268>
93       <function <lambda> at 0x00000227485EE268>
94       <function <lambda> at 0x00000227485EE268>
96       <function <lambda> at 0x00000227485EE268>
101      <function <lambda> at 0x00000227485EE268>
                           ...
26615    <function <lambda> at 0x00000227485EE268>
26616    <function <lambda> at 0x00000227485EE268>
26628    <function <lambda> at 0x00000227485EE268>
26629    <function <lambda> at 0x00000227485EE268>
26632    <function <lambda> at 0x00000227485EE268>
26633    <function <lambda> at 0x00000227485EE268>
26638    <function <lambda> at 0x00000227485EE268>
26639    <function <lambda> at 0x00000227485EE268>
26648    <function <lambda> at 0x00000227485EE268>
26652    <function <lambda> at 0x00000227485EE268>
26656    <function <lambda> at 0x00000227485EE268>
26657    <function <lambda> at 0x00000227485EE268>
26668    <function <lambda> at 0x00000227485EE268>
26670    <function <lambda> at 0x00000227485EE268>
26677    <function <lambda> at 0x00000227485EE268>
26685    <function <lambda> at 0x00000227485EE268>
26688    <function <lambda> at 0x00000227485EE268>
26690    <function <lambda> at 0x00000227485EE268>
26692    <function <lambda> at 0x00000227485EE268>
26694    <function <lambda> at 0x00000227485EE268>
26699    <function <lambda> at 0x00000227485EE268>
26701    <function <lambda> at 0x00000227485EE268>
26703    <function <lambda> at 0x00000227485EE268>
26704    <function <lambda> at 0x00000227485EE268>
26705    <function <lambda> at 0x00000227485EE268>
26708    <function <lambda> at 0x00000227485EE268>
26710    <function <lambda> at 0x00000227485EE268>
26711    <function <lambda> at 0x00000227485EE268>
26716    <function <lambda> at 0x00000227485EE268>
26721    <function <lambda> at 0x00000227485EE268>
Name: AgeuponOutcome, dtype: object

In [11]:
y = load_data['OutcomeType']
y

0        Return_to_owner
1             Euthanasia
2               Adoption
3               Transfer
4               Transfer
5               Transfer
6               Transfer
7               Transfer
8               Adoption
9               Adoption
10              Transfer
11              Adoption
12              Adoption
13       Return_to_owner
14       Return_to_owner
15              Adoption
16              Transfer
17              Transfer
18              Transfer
19       Return_to_owner
20              Transfer
21              Transfer
22              Adoption
23              Adoption
24       Return_to_owner
25              Transfer
26              Adoption
27              Adoption
28              Adoption
29       Return_to_owner
              ...
26699         Euthanasia
26700    Return_to_owner
26701           Transfer
26702               Died
26703           Transfer
26704           Transfer
26705           Transfer
26706           Adoption
26707         Euthanasia
26708           Transfer
26709           Adoption
26710           Transfer
26711           Transfer
26712    Return_to_owner
26713         Euthanasia
26714           Adoption
26715           Adoption
26716           Adoption
26717    Return_to_owner
26718           Adoption
26719           Transfer
26720           Adoption
26721           Adoption
26722           Transfer
26723           Adoption
26724           Transfer
26725           Transfer
26726           Adoption
26727           Transfer
26728           Transfer
Name: OutcomeType, dtype: object